/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.yaakoub.cryptocurrencymarket.api;

import com.yaakoub.cryptocurrencymarket.model.ModelApiResponse;
import com.yaakoub.cryptocurrencymarket.model.User;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-01-29T15:18:53.033Z")
@Api(value = "register", description = "the register API")
@CrossOrigin("http://localhost:4200")
public interface RegisterApi {

    @ApiOperation(value = "Add a new user to the system", nickname = "addUser", notes = "", response = ModelApiResponse.class, tags={ "user", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "successful operation", response = ModelApiResponse.class),
        @ApiResponse(code = 405, message = "Invalid input") })
    @PostMapping(path = "/register")
    ResponseEntity<ModelApiResponse> addUser(@ApiParam(value = "User object that needs to be added to the system", required = true) @Valid @RequestBody User body);

}
